[torizon]
url = "https://dgw.dev.torizon.io/ras/"
server_cert_path = "device-files/root.crt"
client_cert_path = "device-files/client.pem"
client_key_path = "device-files/pkey.pem"

[device]
target_host_port = "127.0.0.1:22"
# If this file does not exist, a new key will be generated and saved to this file
ssh_private_key_path = "./device-key-01.sec"
authorized_keys_path = "./authorized-keys"
