[torizon]
url = "https://dgw.dev.torizon.io:8443/ras"
server_cert_path = "device-files/root.crt"
client_cert_path = "device-files/client.pem"
client_key_path = "device-files/pkey.pem"

[device]
ssh_host_port = "127.0.0.1:22"
ssh_private_key_path = "./device-key.sec"
ssh_public_key_path = "./device-key.pub"
authorized_keys_path = "./authorized-keys"
